#ifndef NUKED_SC55_H
#define NUKED_SC55_H

#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Opaque type. */
struct SC55_Emulator;

typedef enum {
    SC55_OK = 0,
    SC55_ALLOC_FAILED,

    // Caller provided a parameter that is out of range.
    SC55_INVALID_PARAM,

    // TODO: more specific error codes. C++ API needs to return something other than bool.
    SC55_LOADROM_FAILED,

    // TODO: all error codes
} SC55_Error;

SC55_Error SC55_Create(SC55_Emulator** out_emu);
void       SC55_Destroy(SC55_Emulator* emu);

typedef enum {
    SC55_LOADROMS_AUTODETECT,
    SC55_LOADROMS_SC55,
    SC55_LOADROMS_SC55MK2,
    SC55_LOADROMS_JV880,
    // TODO: all romsets
} SC55_LoadRomsType;

/* Load roms from a directory. This should be called after SC55_Create and before any other functions. */
SC55_Error SC55_LoadRoms(SC55_Emulator* emu, const char* directory, SC55_LoadRomsType type);

typedef void(*SC55_SampleCallback)(void* userdata, int32_t left, int32_t right);

/* Sets a callback that will receive sample data as it is generated by the emulator. */
void SC55_SetSampleCallback(SC55_Emulator* emu, SC55_SampleCallback callback, void* userdata);

/* Advances the emulator state. This should be called in a loop to continuously generate sample data. */
void SC55_Step(SC55_Emulator* emu);

/* Post MIDI data to the emulator. This function is threadsafe. */
void SC55_PostMIDI(void* ptr, size_t count);

#ifdef __cplusplus
}
#endif

#endif
